name: Running dwh_filters testcases
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * 5'
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD2_HOST }}
        username: ${{ secrets.CICD2_USERNAME }}
        key: ${{ secrets.CICD2_SECRET }}
        port: ${{secrets.PORT }}
    
        script: |
          sudo git config --global --add safe.directory /apps/github-workflows/DWH-Filters      
          cd /apps/github-workflows/DWH-Filters
          sudo git pull origin master
          sudo git status
          sudo npm install --unsafe-perm=true --allow-root cypress
          sudo npm run cypress:open
